# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#production:
#  <<: *default
#  database: db/production.sqlite3
production:
  url: <%= ENV['DATABASE_URL'] %>